#!/usr/bin/env bash
# install and run nginx web server
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo service nginx start
