#!/usr/bin/env bash
# install and run nginx web server
sudo apt-get update -y
sudo apt-get install nginx -y

echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

put_below="server {"
comment="# Redirections"
query="rewrite ^\/redirect_me youtu.be\/w0AOGeqOnFY permanent;"
sudo sed -i "s/$put_below/$put_below\n\t$comment\n\t$query\n/" /etc/nginx/sites-enabled/default

sudo service nginx start
