#!/usr/bin/env bash
# Fizz Buzz in Bash
for i in {1..100}; do
	str=""

	if [ $((i % 3)) -eq 0 ]; then
		str="Fizz"
	fi
	if [ $((i % 5)) -eq 0 ]; then
		str+="Buzz"
	fi

	if [ -z $str ]; then
		echo $i
	else
		echo $str
	fi
done
