#!/usr/bin/env bash
# Get username, user id and Home directory path for the user from /etc/passwd
FILE="/etc/passwd"

while read -r line; do
	echo "$line" | cut -d ":" -f 1,3,6 | xargs echo
done < $FILE
