#!/usr/bin/env bash
# Bash script that loops from 1 to 10 and display diferent output according to step
i=0
while ((i < 10)); do
	if [ $i -eq 3 ]; then
		echo "bad luck"
	elif [ $i -eq 7 ]; then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	let i++
done
