#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes
i=0; k=1
while ((i <= 12)); do
	echo "Hour: $i"
	while ((k <= 59)); do
		echo $k
		let k++
	done
	let k=1; let i++
done
