#!/usr/bin/env bash
# Bash script that displays, The content of the current directory, In a list format, part after the first dash is displayed
LIST="$(ls)"
for i in $LIST; do
	echo "$i" | cut -d "-" -f 2- | xargs echo
done
